app_group:
  hosts:
    managedhost-app-1:
      ansible_host: app1_ip_address
    managedhost-app-2:
      ansible_host: app2_ip_address
    managedhost-app-3:
      ansible_host: app3_ip_address

load_balancer_group:
  hosts:
    nginx-load-balancer:
      ansible_host: nginx_ip_address
      