app_group:
  hosts:
    managedhost-app-1:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2223  # Adjust this port number based on your docker-compose.yml configuration
      ansible_user: root
    managedhost-app-2:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2224  # Adjust this port number based on your docker-compose.yml configuration
      ansible_user: root
    managedhost-app-3:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2225  # Adjust this port number based on your docker-compose.yml configuration
      ansible_user: root

load_balancer_group:
  hosts:
    localhost:
      ansible_connection: local
