# First Play: Handle Files in all hosts
- name: Play - Handle Files in all hosts
  hosts: all
  tasks:
    - name: all host are identified with a file
      copy:
        content: My family is {{ ansible_os_family }}
        dest: /family.txt
        mode: '777'

# Second Play: Set up Node.js app
- name: Play - for Alpines Nodejs app
  hosts: app_group
  tasks:
    - name: NodeJs is installed
      apk:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      loop:
        - nodejs
        - nodejs-npm
    - name: app directory is created
      file:
        path: /node-app
        state: directory
    - name: app is installed
      template:
        src: app.js.j2
        dest: /node-app/app.js
    - name: app dependencies file is copied
      copy:
        src: package.json
        dest: /node-app/package.json
    - name: app dependencies are installed
      npm:
        path: /node-app
        state: present
        production: true
    - name: Install forever (to run Node.js app)
      npm:
        name: forever
        global: yes
        state: present
    - name: Check list of Node.js apps running
      command: forever list
      register: forever_list
      changed_when: false
    - name: Start example Node.js app
      command: forever start /node-app/app.js
      when: "forever_list.stdout.find('/node-app/app.js') == -1"

# Third Play: Set up Nginx load balancer
- name: Play - Set up Nginx load balancer
  hosts: load_balancer_group
  tasks:
    - name: Start Nginx container
      docker_container:
        name: nginx_load_balancer
        image: nginx:latest
        state: started
        ports:
          - "80:80"
        volumes:
          - "./nginx.conf:/etc/nginx/nginx.conf"
        restart_policy: unless-stopped
        depends_on:
          - managedhost-app-1
          - managedhost-app-2
          - managedhost-app-3
